// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjiybuyudcvfcujvycos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqaXlidXl1ZGN2ZmN1anZ5Y29zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NTU0MzcsImV4cCI6MjA2NjAzMTQzN30.3JBJoIXhs-7nUy0UkEU5SHj9ok6_xR9HffAerkxYabA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);